import { createId } from "./model.js";

export const THEME_VERSION = 1;

const baseTokens = {
  colorScheme: "light",
  appBackground: "#ede9e2",
  paper: "#fbfaf6",
  paperElevated: "#fffefa",
  tray: "#e9e5dd",
  cell: "#fbfaf6",
  cellHover: "#fffefa",
  ink: "#181816",
  defaultInk: "#2c2925",
  muted: "#6f6b64",
  faint: "#9a958d",
  line: "#d8d3ca",
  lineStrong: "#c7c0b5",
  accent: "#b34d35",
  accentSoft: "rgba(179, 77, 53, 0.18)",
  focusRing: "#a94530",
  positive: "#4f6b55",
  negative: "#9b4032",
  selectionBackground: "rgba(179, 77, 53, 0.18)",
  selectionForeground: "#181816",
  surfaceHighlight: "rgba(255,255,255,.82)",
  surfaceHighlightSoft: "rgba(255,255,255,.42)",
  elevationShadow: "rgba(49,41,32,.18)",
  cellRadius: 5,
  cellGap: 1,
  cellHeight: 30,
  columnWidth: 126,
  rowHeaderWidth: 34,
  columnHeaderHeight: 25,
  uiFont: '"Public Sans Variable", "Segoe UI Variable", Arial, sans-serif',
  monoFont: '"Lilex Variable", "Cascadia Mono", Consolas, monospace',
  titleWeight: 620,
  titleTracking: "-0.035em",
  titleSize: 20,
  cellShadow: "inset 0 1px 0 var(--surface-highlight), inset 0 -1px 0 color-mix(in srgb, var(--line-strong) 34%, transparent), 0 1px 1px color-mix(in srgb, var(--elevation-shadow) 44%, transparent), 0 2px 4px color-mix(in srgb, var(--elevation-shadow) 14%, transparent)",
  cellHoverShadow: "inset 0 1px 0 var(--surface-highlight), inset 0 -1px 0 color-mix(in srgb, var(--line-strong) 42%, transparent), 0 3px 7px color-mix(in srgb, var(--elevation-shadow) 72%, transparent)",
};

const darkDepthTokens = {
  colorScheme: "dark",
  surfaceHighlight: "rgba(255,255,255,.06)",
  surfaceHighlightSoft: "rgba(255,255,255,.03)",
  elevationShadow: "rgba(0,0,0,.42)",
  cellShadow: "inset 0 1px 0 var(--surface-highlight), inset 0 -1px 0 color-mix(in srgb, var(--elevation-shadow) 68%, transparent), 0 1px 1px color-mix(in srgb, var(--elevation-shadow) 80%, transparent), 0 2px 5px color-mix(in srgb, var(--elevation-shadow) 48%, transparent)",
  cellHoverShadow: "inset 0 1px 0 var(--surface-highlight), inset 0 -1px 0 color-mix(in srgb, var(--elevation-shadow) 76%, transparent), 0 3px 8px var(--elevation-shadow)",
};

function builtInTheme(id, name, description, tokens = {}) {
  const resolvedTokens = {
    ...baseTokens,
    ...(tokens.colorScheme === "dark" ? darkDepthTokens : {}),
    ...tokens,
  };
  if (!Object.prototype.hasOwnProperty.call(tokens, "defaultInk")) {
    resolvedTokens.defaultInk = tokens.ink || baseTokens.defaultInk;
  }
  return {
    id,
    name,
    description,
    version: THEME_VERSION,
    builtIn: true,
    tokens: resolvedTokens,
  };
}

export const BUILT_IN_THEMES = [
  builtInTheme(
    "paper-public",
    "Tactile Day",
    "Warm ivory, rust focus, Public Sans and Lilex.",
  ),
  builtInTheme(
    "paper-slate",
    "Slate Paper",
    "A cool technical paper with a quiet blue focus.",
    {
      appBackground: "#e8ebeb",
      paper: "#f7f8f6",
      paperElevated: "#fcfdfb",
      tray: "#e2e6e5",
      cell: "#f7f8f6",
      cellHover: "#ffffff",
      ink: "#192022",
      muted: "#637074",
      faint: "#929da0",
      line: "#cfd6d5",
      lineStrong: "#bac5c5",
      accent: "#476d82",
      accentSoft: "rgba(71,109,130,.17)",
      focusRing: "#3e657a",
      selectionBackground: "rgba(71,109,130,.17)",
      selectionForeground: "#192022",
    },
  ),
  builtInTheme(
    "paper-moss",
    "Moss Paper",
    "Soft archival stock with an olive working accent.",
    {
      appBackground: "#ebeade",
      paper: "#faf9ef",
      paperElevated: "#fffef5",
      tray: "#e6e4d6",
      cell: "#faf9ef",
      cellHover: "#fffef7",
      ink: "#202019",
      muted: "#706f60",
      faint: "#999786",
      line: "#d5d2c2",
      lineStrong: "#c3bfab",
      accent: "#69734b",
      accentSoft: "rgba(105,115,75,.18)",
      focusRing: "#5d6841",
      selectionBackground: "rgba(105,115,75,.18)",
      selectionForeground: "#202019",
    },
  ),
  builtInTheme(
    "paper-plum",
    "Plum Paper",
    "Neutral paper warmed by a restrained editorial plum.",
    {
      appBackground: "#ece7e8",
      paper: "#faf7f7",
      paperElevated: "#fffdfd",
      tray: "#e7e0e2",
      cell: "#faf7f7",
      cellHover: "#fffdfd",
      ink: "#211c1e",
      muted: "#72666a",
      faint: "#9b8f93",
      line: "#d9ced1",
      lineStrong: "#c7b9bd",
      accent: "#7d5264",
      accentSoft: "rgba(125,82,100,.18)",
      focusRing: "#704659",
      selectionBackground: "rgba(125,82,100,.18)",
      selectionForeground: "#211c1e",
    },
  ),
  builtInTheme(
    "github-dark",
    "GitHub Dark",
    "GitHub Primer's dark canvas and clear blue interaction color.",
    {
      ...darkDepthTokens,
      appBackground: "#010409",
      paper: "#0d1117",
      paperElevated: "#161b22",
      tray: "#161b22",
      cell: "#0d1117",
      cellHover: "#161b22",
      ink: "#e6edf3",
      muted: "#8b949e",
      faint: "#6e7681",
      line: "#21262d",
      lineStrong: "#30363d",
      accent: "#2f81f7",
      accentSoft: "rgba(47,129,247,.22)",
      focusRing: "#58a6ff",
      positive: "#3fb950",
      negative: "#f85149",
      selectionBackground: "rgba(47,129,247,.32)",
      selectionForeground: "#f0f6fc",
    },
  ),
  builtInTheme(
    "catppuccin-dark",
    "Catppuccin Dark",
    "Catppuccin Mocha's cozy base with soft pastel blue focus.",
    {
      ...darkDepthTokens,
      appBackground: "#11111b",
      paper: "#1e1e2e",
      paperElevated: "#313244",
      tray: "#181825",
      cell: "#1e1e2e",
      cellHover: "#313244",
      ink: "#cdd6f4",
      muted: "#a6adc8",
      faint: "#7f849c",
      line: "#313244",
      lineStrong: "#45475a",
      accent: "#89b4fa",
      accentSoft: "rgba(137,180,250,.22)",
      focusRing: "#b4befe",
      positive: "#a6e3a1",
      negative: "#f38ba8",
      selectionBackground: "rgba(137,180,250,.28)",
      selectionForeground: "#cdd6f4",
    },
  ),
  builtInTheme(
    "flexoki-light",
    "Flexoki Light",
    "Warm digital paper with Flexoki's inky, high-contrast palette.",
    {
      appBackground: "#f2f0e5",
      paper: "#fffcf0",
      paperElevated: "#fffef7",
      tray: "#e6e4d9",
      cell: "#fffcf0",
      cellHover: "#fffef7",
      ink: "#100f0f",
      muted: "#6f6e69",
      faint: "#9f9d96",
      line: "#e6e4d9",
      lineStrong: "#dad8ce",
      accent: "#24837b",
      accentSoft: "rgba(36,131,123,.18)",
      focusRing: "#205ea6",
      positive: "#66800b",
      negative: "#af3029",
      selectionBackground: "rgba(36,131,123,.22)",
      selectionForeground: "#100f0f",
    },
  ),
  builtInTheme(
    "flexoki-dark",
    "Flexoki Dark",
    "Warm black ink reversed into Flexoki's low-glare dark paper.",
    {
      ...darkDepthTokens,
      appBackground: "#100f0f",
      paper: "#1c1b1a",
      paperElevated: "#282726",
      tray: "#100f0f",
      cell: "#1c1b1a",
      cellHover: "#282726",
      ink: "#cecdc3",
      muted: "#878580",
      faint: "#6f6e69",
      line: "#282726",
      lineStrong: "#403e3c",
      accent: "#3aa99f",
      accentSoft: "rgba(58,169,159,.2)",
      focusRing: "#4385be",
      positive: "#879a39",
      negative: "#d14d41",
      selectionBackground: "rgba(58,169,159,.27)",
      selectionForeground: "#cecdc3",
    },
  ),
  builtInTheme(
    "one-dark",
    "Tactile Night",
    "Atom's graphite workspace with the familiar One Dark blue.",
    {
      ...darkDepthTokens,
      appBackground: "#21252b",
      paper: "#282c34",
      paperElevated: "#2c313c",
      tray: "#21252b",
      cell: "#282c34",
      cellHover: "#2c313c",
      ink: "#abb2bf",
      muted: "#828997",
      faint: "#5c6370",
      line: "#3e4451",
      lineStrong: "#4b5263",
      accent: "#61afef",
      accentSoft: "rgba(97,175,239,.2)",
      focusRing: "#528bff",
      positive: "#98c379",
      negative: "#e06c75",
      selectionBackground: "rgba(82,139,255,.3)",
      selectionForeground: "#abb2bf",
    },
  ),
  builtInTheme(
    "nord-dark",
    "Nord Dark",
    "Nord's Polar Night surfaces with a crisp Frost accent.",
    {
      ...darkDepthTokens,
      appBackground: "#2e3440",
      paper: "#3b4252",
      paperElevated: "#434c5e",
      tray: "#2e3440",
      cell: "#3b4252",
      cellHover: "#434c5e",
      ink: "#eceff4",
      muted: "#d8dee9",
      faint: "#aeb7c5",
      line: "#434c5e",
      lineStrong: "#4c566a",
      accent: "#88c0d0",
      accentSoft: "rgba(136,192,208,.2)",
      focusRing: "#5e81ac",
      positive: "#a3be8c",
      negative: "#bf616a",
      selectionBackground: "rgba(136,192,208,.28)",
      selectionForeground: "#eceff4",
    },
  ),
  builtInTheme(
    "vscode-dark",
    "VSCode Dark",
    "Visual Studio Code's focused charcoal workspace and blue accent.",
    {
      ...darkDepthTokens,
      appBackground: "#181818",
      paper: "#1e1e1e",
      paperElevated: "#252526",
      tray: "#181818",
      cell: "#1e1e1e",
      cellHover: "#2a2d2e",
      ink: "#cccccc",
      muted: "#a0a0a0",
      faint: "#858585",
      line: "#2b2b2b",
      lineStrong: "#3c3c3c",
      accent: "#007acc",
      accentSoft: "rgba(0,122,204,.24)",
      focusRing: "#007fd4",
      positive: "#89d185",
      negative: "#f14c4c",
      selectionBackground: "rgba(0,122,204,.36)",
      selectionForeground: "#ffffff",
    },
  ),
  builtInTheme(
    "macos-light",
    "macOS Light",
    "A bright system-like canvas with layered neutral surfaces.",
    {
      appBackground: "#f2f2f7",
      paper: "#ffffff",
      paperElevated: "#ffffff",
      tray: "#e5e5ea",
      cell: "#ffffff",
      cellHover: "#f7f7f9",
      ink: "#1c1c1e",
      muted: "#636366",
      faint: "#8e8e93",
      line: "#d1d1d6",
      lineStrong: "#aeaeb2",
      accent: "#007aff",
      accentSoft: "rgba(0,122,255,.16)",
      focusRing: "#0a84ff",
      positive: "#248a3d",
      negative: "#d70015",
      selectionBackground: "rgba(0,122,255,.22)",
      selectionForeground: "#1c1c1e",
    },
  ),
  builtInTheme(
    "macos-dark",
    "macOS Dark",
    "A layered system-like dark appearance with luminous blue focus.",
    {
      ...darkDepthTokens,
      appBackground: "#000000",
      paper: "#1c1c1e",
      paperElevated: "#2c2c2e",
      tray: "#141416",
      cell: "#1c1c1e",
      cellHover: "#2c2c2e",
      ink: "#f2f2f7",
      muted: "#aeaeb2",
      faint: "#8e8e93",
      line: "#38383a",
      lineStrong: "#48484a",
      accent: "#0a84ff",
      accentSoft: "rgba(10,132,255,.23)",
      focusRing: "#64d2ff",
      positive: "#30d158",
      negative: "#ff453a",
      selectionBackground: "rgba(10,132,255,.32)",
      selectionForeground: "#ffffff",
    },
  ),
  builtInTheme(
    "notion-light",
    "Notion Light",
    "A quiet white workspace with warm graphite text and soft rules.",
    {
      appBackground: "#f7f7f5",
      paper: "#ffffff",
      paperElevated: "#ffffff",
      tray: "#f1f1ef",
      cell: "#ffffff",
      cellHover: "#f7f7f5",
      ink: "#37352f",
      muted: "#787774",
      faint: "#9b9a97",
      line: "#e9e9e7",
      lineStrong: "#d3d3d0",
      accent: "#2383e2",
      accentSoft: "rgba(35,131,226,.14)",
      focusRing: "#2383e2",
      positive: "#0f7b6c",
      negative: "#e03e3e",
      selectionBackground: "rgba(35,131,226,.2)",
      selectionForeground: "#37352f",
    },
  ),
  builtInTheme(
    "notion-dark",
    "Notion Dark",
    "A calm near-black workspace with restrained Notion-like contrast.",
    {
      ...darkDepthTokens,
      appBackground: "#141414",
      paper: "#191919",
      paperElevated: "#252525",
      tray: "#202020",
      cell: "#191919",
      cellHover: "#252525",
      ink: "#f2f2f2",
      muted: "#b3b3b3",
      faint: "#8b8b8b",
      line: "#2f2f2f",
      lineStrong: "#434343",
      accent: "#529cca",
      accentSoft: "rgba(82,156,202,.22)",
      focusRing: "#6aa9d0",
      positive: "#4dab9a",
      negative: "#ff7369",
      selectionBackground: "rgba(82,156,202,.3)",
      selectionForeground: "#ffffff",
    },
  ),
];

export function normalizeTheme(theme) {
  if (!theme || typeof theme !== "object") throw new Error("This is not a Tactile theme.");
  const providedTokens = theme.tokens && typeof theme.tokens === "object" ? theme.tokens : {};
  const tokens = {
    ...baseTokens,
    ...(providedTokens.colorScheme === "dark" ? darkDepthTokens : {}),
    ...providedTokens,
  };
  return {
    ...theme,
    id: String(theme.id || createId("theme")),
    name: String(theme.name || "Imported theme"),
    description: String(theme.description || ""),
    version: Number(theme.version || THEME_VERSION),
    builtIn: false,
    tokens: {
      ...tokens,
      defaultInk: providedTokens.defaultInk ?? providedTokens.ink ?? tokens.defaultInk,
      selectionBackground: providedTokens.selectionBackground ?? tokens.accentSoft,
      selectionForeground: providedTokens.selectionForeground ?? tokens.ink,
    },
  };
}

export function resolveTheme(themeId, customThemes = {}) {
  return (customThemes[themeId] ? normalizeTheme(customThemes[themeId]) : null)
    || BUILT_IN_THEMES.find((theme) => theme.id === themeId)
    || BUILT_IN_THEMES[0];
}

export function allThemes(customThemes = {}) {
  return [...BUILT_IN_THEMES, ...Object.values(customThemes).map(normalizeTheme)];
}

export function cloneTheme(theme) {
  return normalizeTheme({
    ...theme,
    id: createId("theme"),
    name: `${theme.name} copy`,
    builtIn: false,
    tokens: { ...theme.tokens },
  });
}

export function themeStyle(theme) {
  const providedTokens = theme?.tokens || {};
  const tokens = {
    ...baseTokens,
    ...providedTokens,
    ...(providedTokens.colorScheme === "dark" ? {
      ...darkDepthTokens,
      ...Object.fromEntries(
        Object.entries(providedTokens).filter(([key]) => !Object.hasOwn(darkDepthTokens, key)),
      ),
    } : {}),
  };
  const selectionBackground = tokens.selectionBackground || tokens.accentSoft;
  const selectionForeground = tokens.selectionForeground || tokens.ink;
  return {
    colorScheme: tokens.colorScheme === "dark" ? "dark" : "light",
    "--app-background": tokens.appBackground,
    "--paper": tokens.paper,
    "--paper-elevated": tokens.paperElevated,
    "--tray": tokens.tray,
    "--cell": tokens.cell,
    "--cell-hover": tokens.cellHover,
    "--ink": tokens.ink,
    "--default-ink": tokens.defaultInk || tokens.ink,
    "--muted": tokens.muted,
    "--faint": tokens.faint,
    "--line": tokens.line,
    "--line-strong": tokens.lineStrong,
    "--accent": tokens.accent,
    "--accent-soft": tokens.accentSoft,
    "--selection-background": selectionBackground,
    "--selection-foreground": selectionForeground,
    "--focus-ring": tokens.focusRing,
    "--surface-highlight": tokens.surfaceHighlight,
    "--surface-highlight-soft": tokens.surfaceHighlightSoft,
    "--elevation-shadow": tokens.elevationShadow,
    "--scrollbar-track": tokens.tray,
    "--scrollbar-thumb": tokens.lineStrong,
    "--scrollbar-thumb-hover": tokens.accent,
    "--positive": tokens.positive,
    "--negative": tokens.negative,
    "--cell-radius": `${tokens.cellRadius}px`,
    "--cell-gap": `${tokens.cellGap}px`,
    "--cell-height": `${tokens.cellHeight}px`,
    "--font-display": tokens.uiFont,
    "--font-ui": tokens.uiFont,
    "--font-description": tokens.uiFont,
    "--font-body": tokens.uiFont,
    "--font-mono": tokens.monoFont,
    "--title-weight": tokens.titleWeight,
    "--title-tracking": tokens.titleTracking,
    "--title-size": `${tokens.titleSize}px`,
    "--cell-shadow": tokens.cellShadow,
    "--cell-hover-shadow": tokens.cellHoverShadow,
  };
}

export function themeSheetMetrics(theme) {
  const tokens = { ...baseTokens, ...(theme?.tokens || {}) };
  return {
    rowHeight: Math.max(24, Number(tokens.cellHeight) + Number(tokens.cellGap)),
    columnWidth: Math.max(76, Number(tokens.columnWidth)),
    rowHeaderWidth: Math.max(28, Number(tokens.rowHeaderWidth)),
    columnHeaderHeight: Math.max(20, Number(tokens.columnHeaderHeight)),
    bodyLeftInset: 3,
    bodyTopInset: 3,
    overscan: 3,
  };
}

export function downloadTheme(theme) {
  const portable = normalizeTheme(theme);
  const blob = new Blob([JSON.stringify(portable, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${portable.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.tactile-theme.json`;
  anchor.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export async function themeFromFile(file) {
  return normalizeTheme(JSON.parse(await file.text()));
}
